name: dave
channels:
- conda-forge
- defaults
dependencies:
- autopep8
- convertdate
- dateparser
- ephem
- google-api-python-client
- httplib2
- jdatetime
- oauth2client
- pluginbase
- pyasn1
- pyasn1-modules
- pycodestyle
- python-dateutil
- pytz
- rsa
- ruamel.yaml
- simplejson
- tzlocal
- umalqurra
- uritemplate
- aiohttp
- asn1crypto
- async-timeout
- ca-certificates
- certifi
- cffi
- chardet
- cryptography
- cymem
- cytoolz
- dbus
- dill
- expat
- ftfy
- gettext
- glib
- html5lib
- icu
- idna
- intel-openmp
- jpeg
- libcxx
- libcxxabi
- libedit
- libffi
- libgfortran
- libiconv
- libpng
- lockfile
- mkl
- msgpack-numpy
- msgpack-python
- multidict
- murmurhash
- ncurses
- numpy
- openssl
- pathlib
- pcre
- pep8
- pip
- plac
- preshed
- pycparser
- pyopenssl
- pysocks
- python
- python-daemon
- python-engineio
- python-socketio
- readline
- regex
- requests
- setuptools
- sip
- six
- spacy
- sqlite
- termcolor
- thinc
- tk
- toolz
- tqdm
- ujson
- urllib3
- wcwidth
- webencodings
- wheel
- wrapt
- xz
- yarl
- zlib
- pip:
  - beautifulsoup4
  - en-core-web-sm
  - fuzzywuzzy
  - lxml
  - pyaudio
  - pyqt5
  - python-levenshtein
  - speechrecognition

